import streamlit as st
import time
from utils.utils import YouTubeSummaryService

st.set_page_config(page_title="YouTube Video Summarizer", layout="centered")

MODEL_MAPPING = {
    "DeepSeek R1": "deepseek-r1-distill-llama-70b",
    "Llama 8B": "llama3-8b-8192",
    "Llama 70B": "llama3-70b-8192",
    "Gemini": "gemma2-9b-it",
    "Mixtral": "mixtral-8x7b-32768"
}

st.title("🎥 YouTube Video Summarizer")

with st.sidebar:
    st.title("Chatbot Settings")

    selected_model = st.selectbox("Select Model", list(MODEL_MAPPING.keys()))
    model_name = MODEL_MAPPING[selected_model]

if "summarizer_service" not in st.session_state:
    st.session_state.summarizer_service = YouTubeSummaryService()

if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "assistant", 
         "content": ""}
    ]

st.write("Hi! I'm your YouTube Video Summarizer. Paste a YouTube video URL, select a model, and I'll generate a summary for you! 🎬")

if video_url := st.chat_input("Enter a YouTube video URL to summarize"):
    try:
        if(not st.session_state.summarizer_service.is_valid_youtube_url(video_url)):
            with st.chat_message("assistant", avatar="🤖"):
                st.error("⚠️ Invalid YouTube video URL. Please enter a valid URL.")
        else :
            with st.chat_message("user", avatar="👤"):
                st.markdown(video_url)

            with st.spinner("Generating Summary: "):
                start_time = time.process_time()
                transcript_text = st.session_state.summarizer_service.get_transcript_from_video(video_url)
                elapsed_time = time.process_time() - start_time
                
                with st.chat_message("assistant", avatar="🤖"):
                    st.markdown("## Transcript")
                    st.markdown(transcript_text, unsafe_allow_html=True)
                    # st.markdown(bot_response, unsafe_allow_html=True)
                    st.caption(f"🟡 *Response generated by {selected_model}* – ⏳ {elapsed_time:.2f} sec")

    except Exception as e:
        with st.chat_message("assistant", avatar="🤖"):
            st.error(f"⚠️ Error generating response: {str(e)}")

